### ISSUE TITLE
About the points in each bin

### ISSUE THREAD

**Issue by leon-liangwu** [zuokai/roialign#5]
@zuokai 
According to the paper, there is a max pooling or average pooling after the bilinear interpolation. I found that in your code, you use the bilinear interpolation value of the center point in each bin as the roi feature value.
I am a little confused by this operation.
Could you please explain that to me?

**Comment by zuokai** [comment]
you can see the roi_align_layer.cu, not the roi_align_layer.cpp, in the gpu version, you can set is_multi_interpolate = true.
in the cpu version, only interpolate one time, since the paper says: "In fact, interpolating only a single value at each bin center (without pooling) is nearly as effective. "(in page 3)

**Comment by zuokai** [comment]
since I only use the gpu version，so I didn‘t implement “multi-interpolate” in the cpp，so I suggest you using the gpu version.

**Comment by leon-liangwu** [comment]
Ok, I see. Thanks.
